spring:
  application:
    name: gatewayserver
  config:
    import: optional:configserver:http://localhost:8071
management:
  endpoint:
    gateway:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1