spring:
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8071
  zipkin:
    base-url: http://localhost:9411
  cloud:
    function:
      definition: receiveOrderStatus
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          enable-observation: true
      bindings:
        receiveOrderStatus-in-0:
          destination: orderStatus
  sleuth:
    feign:
      enabled: true
    integration:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1
