spring:
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8071
  application:
    name: cartserver
  sleuth:
    feign:
      enabled: true
    integration:
      enabled: true
    sampler:
      percentage: 1