spring:
  application:
    name: notificationserver
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8071
  zipkin:
    base-url: http://localhost:9411
  cloud:
    function:
      definition: receiveSomeMessage
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          enable-observation: true
      bindings:
        receiveSomeMessage-in-0:
          destination: orderStatus
        getCartForReceipt-in-0:
          destination: finishedUserCart
  sleuth:
    integration:
      enabled: true
management:
  tracing:
    sampling:
      probability: 1