services:
  elasticsearch:
    image: elasticsearch:7.7.0
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    restart: unless-stopped
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.name=docker-cluster
      - "network.host=0.0.0.0"     # <-- вот это
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9300:9300"
      - "9200:9200"
    healthcheck:
      test: 'curl -f http://localhost:9200 || exit 1'
    profiles: ["prod"]
#    networks:
#      backend:
#        aliases:
#          - "elasticsearch"
  kibana:
    image: kibana:7.7.0
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9300"
    ports:
      - "5601:5601"
    profiles: ["prod"]
#    networks:
#      backend:
#        aliases:
#          - "kibana"
  logstash:
    image: logstash:7.7.0
    command:
      logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    profiles: ["prod"]
#    networks:
#      backend:
#        aliases:
#          - "logstash"
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - keycloak:/opt/keycloak/data/
    ports:
      - "8090:8080"
    command:
      - "start-dev"
    profiles: ["dev", "prod"]
  zipkin:
    image: openzipkin/zipkin:3.4.1
    depends_on:
      - elasticsearch
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=http://elasticsearch:9200
      #- ES_HTTP_LOGGING=BASIC
    ports:
      - "9411:9411"
    profiles: ["prod"]
#    networks:
#      backend:
#        aliases:
#          - "zipkin"
  zipkin-dev:
    image: openzipkin/zipkin:3.4.1
    ports:
      - "9411:9411"
    profiles: ["dev", "prod"]
  #    networks:
  #      backend:
  #        aliases:
  #          - "zipkin"
  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    profiles: ["dev", "prod"]
volumes:
  keycloak:
    driver: local
  elasticsearch:
    driver: local