spring:
  application:
    name: deliveryserver
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8071
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    integration:
      enabled: true
  cloud:
    function:
      definition: getUserCart
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          enable-observation: true
      bindings:
        getUserCart-in-0:
          destination: userCart
          content-type: application/json
        output-out-0:
          destination: orderStatus
#          producer:
#            partition-count: 2
#            partition-key-expression: headers.id
management:
  tracing:
    sampling:
      probability: 1
